bsite:
  # radius (in Angstroms) around ligands for which residues are considered to be part of the binding site
  radius: 5
template:
  radius: 2

plddt:
  threshold: 50
# structures parameter decides whether to calculate `whole` structure, substructure aligned with `template` or `bsite`.
# `plddt` means that the loops with low plddt are removed
# resources/templates has to be present and contain valid structures for last 2 to work
# plddt works only for alphafold structures, since plddt is written in the b-factor there
structures: template

# If set to true, only computes the proteins data (useful for pretraining)
only_proteins: false

# Seed for reproducibility of random processes
seed: 42

prepare_proteins:
  # can be label or onehot
  node_feats: label
  # can be label, onehot or none
  edge_feats: label
  shard_size: 10000

prepare_drugs:
  max_num_atoms: 150
  node_feats: label
  edge_feats: label

split:
  # available methods: random, coldtarget, colddrug
  method: colddrug
  train: 0.7
  val: 0.2
  # test is created as a remainder of train and val

parse_dataset:
  # filtering can be posneg, balanced or all
  filtering: posneg
  # sampling
  # sampling can be over, under or none
  sampling: under
  # class or reg
  task: class
  # threshold values for class problem
  threshold: 100
  # Whether to apply logarithm with base of 10 to values (for reg, doesn't affect threshold  )
  log: false
